[package]
name = "banking_mainframe"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.7"
diesel = { version = "2.3.4", features = ["postgres"] }
dotenvy = "0.15.7"
tokio = { version = "1.32.0", features = ["full"] }
